### ISSUE TITLE
_bbox_transform_inv: Could not broadcast input array

### ISSUE THREAD

**Issue by lunzueta** [mitmul/chainer-faster-rcnn#1]
Hi @mitmul. I'm testing this program in Windows 10 64-bits (Anaconda + Pycharm), following your instructions.

The first error I found was in the file cpu_nms.pyx, line 26: `cdef np.ndarray[np.int_t, ndim=1] order = scores.argsort()[::-1]`, where the error was `ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'`. This can be fixed by replacing `int_t` with `int64_t` (in a similar way as suggested in https://github.com/rbgirshick/py-faster-rcnn/issues/36).

After fixing that error, I get another error in the file bbox_transform.py, line 73, in _bbox_transform_inv:
    `pred_boxes[:, 0::4] = pred_ctr_x - 0.5 * pred_w`
`ValueError: could not broadcast input array from shape (300,21) into shape (1,21)`

I'm stuck with this. Any suggestion?

**Comment by mitmul** [comment]
Hi @lunzueta, unfortunately I don't have any computer that can run Windows, so I haven't tested anything with Windows. So I didn't notice that error so thank you for letting me know the first error.

As for the second error, that's a known bug of Chainer. Please see [this PR to Chainer](https://github.com/pfnet/chainer/pull/1273) (and actually I wrote about this in my README.md, but sorry I guess it's hard to notice). I think some people have installed Chainer via pip, so it could be pain to apply diff to the Chainer's source. So I've fixed this problem by replacing the Chainer's roi_pooling_2d function with my modified one at [this commit](https://github.com/mitmul/chainer-faster-rcnn/commit/4edf1feff3f895ffc06d4852598e51f24c2fefbe).

Could you run `git pull` and try it again?

**Comment by lunzueta** [comment]
Thank you @mitmul. That solved the problem. Yes, I installed chainer via pip and I didn't realize about that comment in the description :-P
