### ISSUE TITLE
cupy issue in CPU only environment 

### ISSUE THREAD

**Issue by cloudtoro** [mitmul/chainer-faster-rcnn#12]
Hi,

I was trying the latest version as of Nov 17 2016.

When I ran forward.py in a CPU only environement, the following error was encountered:

File "forward.py", line 89, in <module>
    cls_score, bbox_pred = model(img, np.array([[h, w, im_scale]]))
File "....lib/models/faster_rcnn.py", line 46, in __call__
   if isinstance(im_info, chainer.cuda.cupy.ndarray):
AttributeError: 'module' object has no attribute 'cupy'

Are there any changes needed for it to run in without GPU?

Thanks!
cloudtoro

**Comment by yawara** [comment]
I have the same issue in macOS Sierra.

**Comment by zhikliao** [comment]
Hi,
I have the same problems with you guys. I'm not sure if the cause is "CPU only environment" yet, but if you guys have any idea about how to solve this, please share with me. Thanks~ ^_^

**Comment by mitmul** [comment]
Sorry, I added another condition before checking the instance type of im_info in the faster_rcnn.py to see the cuda availablity. Please pull the master branch and try it again.

**Comment by shrishtrived** [comment]
Same issue cannot run with CPU environment . Can anyone tell what modifications to be made for running it on CPU, thanks.

**Comment by shrishtrived** [comment]
It's working with master type, thank you.

**Comment by mitmul** [comment]
@cloudtoro @yawara @zhikliao @shrishtrived Hi, thank you for trying this chainer-faster-rcnn codes. We've released the new clean & simple & reliable (it surely reproduced the paper result) version of Faster R-CNN inference & training codes as ChainerCV: https://github.com/pfnet/chainercv . I think the problem discussed here has been solved in ChainerCV. Please check the ChainerCV repo!
