### ISSUE TITLE
再学習でエラー

### ISSUE THREAD

**Issue by PixelDotZero** [mitmul/chainer-faster-rcnn#19]
いつも参考にさせて頂いております。
chainer-faster-rcnnの再学習に挑戦していたところ、
モデルデータの読み込みでエラーが発生しました

----

Tracebask (most recent call last):
  File "train.py", line 37, in <module>
    args.trunk_file, args.trunk_name, args.trunk_param, True, result_dir)
  File "****/chainer-faster-rcnn/utils/prepare_train.py", line 185, in get_model
    for trunk_name in trunk.leys():
AttributeError: 'CaffeFunction' object has no attribute 'keys'

----

モデルデータは下記を参考にVGG16.modelを作成
https://github.com/mitmul/chainer-faster-rcnn/issues/15
モデルデータのサイズは下記の通りです
入力:VGG_ILSVRV_16_layers.caffemodel 553,432,081byte
出力:VGG16.model 3,778,049,090byte

エラーの原因に心当たりありましたら、ご教示いただけないでしょうか？
また、モデルデータのサイズは妥当でしょうか？

■テスト環境
ubuntu 14.04LTS
python 2.7.6
chainer 1.21.0
numpy 1.12.0
protobuf 3.2.0
pycuda 2016.1.1
CUDA 8.0

**Comment by apple2373** [comment]
FYI https://drive.google.com/open?id=0B046sNk0DhCDWmt6Wm9lSkFlNGM

**Comment by clockwiser** [comment]
I met the same problem. There is a hint about using VGG16 model.
https://github.com/mitmul/chainer-faster-rcnn/issues/15

For example, the following code creates vgg16 model directly.
*************************************************************************
from chainer.links.caffe import CaffeFunction
model = CaffeFunction('VGG_ILSVRC_16_layers.caffemodel')
*************************************************************************
I tried it in the get_model() function in prepare_train.py.
But failed with the following error. 
ValueError: dictionary update sequence element #0 has length 3; 2 is required

**Comment by clockwiser** [comment]
Actually another way of fine tuning in chainer is copying caffe model to a customized model.
*******************************
def copy_model(src, dst):
    assert isinstance(src, link.Chain)
    assert isinstance(dst, link.Chain)
    for child in src.children():
        if child.name not in dst.__dict__: continue
        dst_child = dst[child.name]
        if type(child) != type(dst_child): continue
        if isinstance(child, link.Chain):
            copy_model(child, dst_child)
        if isinstance(child, link.Link):
            match = True
            for a, b in zip(child.namedparams(), dst_child.namedparams()):
                if a[0] != b[0]:
                    match = False
                    break
                if a[1].data.shape != b[1].data.shape:
                    match = False
                    break
            if not match:
                print ('Ignore %s because of parameter mismatch' % child.name)
                continue
            for a, b in zip(child.namedparams(), dst_child.namedparams()):
                b[1].data = a[1].data
            print ('Copy %s' % child.name)
***************************************************
Tried the following code.
vgg16 = CaffeFunction('data/VGG_ILSVRC_16_layers.caffemodel')
copy_model(vgg16, model) 

This time strangely only two layers are copied, then failed with an memory error.

Copy fc6
Copy fc7
2017-03-09 23:04:39,362 [INFO] train: 6301, valid: 6307
Traceback (most recent call last):
  File "train.py", line 86, in <module>
    trainer.run()
 )
  File "cupy/cuda/runtime.pyx", line 207, in cupy.cuda.runtime.malloc (cupy/cuda/runtime.cpp:3429)
  File "cupy/cuda/runtime.pyx", line 130, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:2241)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

My machine has 32GB memory and 4GB gpu memory. Don't know how much memory is required to run it.

**Comment by clockwiser** [comment]
The model defined in the faster_rcnn.py seems different from the VGG16 model recommended.

self.add_link('trunk', trunk())
        self.add_link('RPN', RPN(rpn_in_ch, rpn_out_ch, n_anchors, feat_stride,
                                 anchor_scales, num_classes, rpn_sigma))
        self.add_link('fc6', L.Linear(25088, 4096))
        self.add_link('fc7', L.Linear(4096, 4096))
        self.add_link('cls_score', L.Linear(4096, num_classes))
        self.add_link('bbox_pred', L.Linear(4096, num_classes * 4))

**Comment by clockwiser** [comment]
Finally find out the reason of trouble.
The default model of train.py is faster rcnn, but vgg16 is tried to initialize the default model. It also explains why only two conv layers were copied when copy_model was used.
The right model also can be downloaded.See below script.
https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/scripts/fetch_faster_rcnn_models.sh

**Comment by clockwiser** [comment]
This problem happens when try to np.load a pickled file and get the keys.
Solved the problem as below.
**************************************************************
vgg16 = CaffeFunction('data/VGG_ILSVRC_16_layers.caffemodel') 
copy_model(vgg16, model.trunk) 
******************************************************
After running the train.py, initialization of trunk looks ok.

2017-03-11 00:01:12,357 [INFO] Start loading pre-trained trunk parameters...
Copy conv1_1
Copy conv1_2
Copy conv2_1
Copy conv2_2
Copy conv3_1
Copy conv3_2
Copy conv3_3
Copy conv4_1
Copy conv4_2
Copy conv4_3
Copy conv5_1
Copy conv5_2
Copy conv5_3

**Comment by PixelDotZero** [comment]
@apple2373 Thank you for data provision.
Unfortunately it was not improved.

**Comment by apple2373** [comment]
Strange... It worked for with the old underlined way....

**Comment by PixelDotZero** [comment]
@clockwiser Thanks for the response.
I also try using get_model ()...

**Comment by chengs2000** [comment]
Got same problem!

@PixelDotZero , @clockwiser 
how did you try it in get_model() method in prepare_train.py?

**Comment by mitmul** [comment]
I'm sorry for the inconvenience. Now I'm fixing problems reported here and in the other issues and planning to merge the `v2` branch as soon as possible. So please kindly wait for the update.

**Comment by clockwiser** [comment]
R-cnn model has two parts. Vgg model should be copied to the Trunk part. Otherwise happens this 'keys' error.

**Comment by chengs2000** [comment]
@clockwiser ,
After creating VGG16.model model, I put it in the data directory.
If I run "python train.py", the parameters related to the Trunk part are
trunk_file='lib/models/vgg16.py', trunk_name='VGG16', trunk_param='data/VGG16.model'.

Anything else I need to do? Thanks.

**Comment by clockwiser** [comment]
@chengs2000 
1. Add a new method called copy_model.
2. Copy VGG data to Trunk using copy_model.
Modified source(prepare_train.py) is as below.

`# new copy method
def copy_model(src, dst):
    assert isinstance(src, link.Chain)
    assert isinstance(dst, link.Chain)
    for child in src.children():
        if child.name not in dst.__dict__: continue
        dst_child = dst[child.name]
        if type(child) != type(dst_child): continue
        if isinstance(child, link.Chain):
            copy_model(child, dst_child)
        if isinstance(child, link.Link):
            match = True
            for a, b in zip(child.namedparams(), dst_child.namedparams()):
                if a[0] != b[0]:
                    match = False
                    break
                if a[1].data.shape != b[1].data.shape:
                    match = False
                    break
            if not match:
                print ('Ignore %s because of parameter mismatch' % child.name)
                continue
            for a, b in zip(child.namedparams(), dst_child.namedparams()):
                b[1].data = a[1].data
            print ('Copy %s' % child.name)
            
def get_model(
        model_file, model_name, gpu, rpn_in_ch, rpn_out_ch, n_anchors,
        feat_stride, anchor_scales, num_classes, spatial_scale, rpn_sigma,
        sigma, trunk_file, trunk_name, trunk_param, train=False,
        result_dir=None):
    model = imp.load_source(model_name, model_file)
    model = getattr(model, model_name)
    if trunk_name is not None and trunk_file is not None:
        trunk = imp.load_source(trunk_name, trunk_file)
        trunk = getattr(trunk, trunk_name)

    # Initialize
    model = model(
        gpu=gpu, trunk=trunk, rpn_in_ch=rpn_in_ch, rpn_out_ch=rpn_out_ch,
        n_anchors=n_anchors, feat_stride=feat_stride,
        anchor_scales=anchor_scales, num_classes=num_classes,
        spatial_scale=spatial_scale, rpn_sigma=rpn_sigma, sigma=sigma)

    # Load pre-trained trunk params
    if trunk_file is not None and trunk_name is not None \
            and trunk_param is not None:
        logging.info('Loading pre-trained trunk parameters...')
        vgg16 = CaffeFunction('data/VGG_ILSVRC_16_layers.caffemodel')
       # here copy vgg16 to trunk.
        copy_model(vgg16, model.trunk) 
        logging.info('End loading pre-trained trunk parameters...')
       #comment out the following part.
        """
        trunk = np.load(trunk_param)
        for name, param in model.namedparams():
            if 'trunk' not in name:
                continue
            for trunk_name in trunk.keys():
                if trunk_name in name:
                    target = model.trunk
                    names = [n for n in trunk_name.split('/') if len(n) > 0]
                    for n in names[:-1]:
                        target = target.__dict__[n]
                    logging.info('{}: {} <- {}'.format(
                        trunk_name, target.__dict__[names[-1]].data.shape,
                        trunk[trunk_name].shape))
                    target.__dict__[names[-1]].data = trunk[trunk_name]
        """
`

**Comment by chengs2000** [comment]
@clockwiser , Thanks for the code.
I added the new method copy_model in the prepare_train.py.
But when I run the training again. I got the following error of the "assert isinstance(src, link.Chain)":
NameError: name 'link' is not defined.

I did not find where you define 'link'.

**Comment by clockwiser** [comment]
from chainer.links.caffe import CaffeFunction
from chainer.links import VGG16Layers
from chainer import link, Chain, optimizers, Variable

**Comment by chengs2000** [comment]
@clockwiser, thanks for the help.
I get the following error for the line: 
if child.name not in dst.dict: continue
AttributeError: 'VGG16' object has no attribute 'dict'

**Comment by clockwiser** [comment]
@chengs2000 
Did you comment out the lines starting at 'trunk = np.load' ?
My machine runs with the above code with no problem.
It is recursive copy between models. Shouldn't be errors between different models.

**Comment by chengs2000** [comment]
@clockwiser 
Yes, I commented out the lines starting at 'trunk = np.load'.
The above problem happened in the method of copy_model(src, dst), line 5:
if child.name not in dst.dict: continue

By the way, May I have your prepare_train.py?
Thanks.

**Comment by clockwiser** [comment]
@chengs2000 ,

I found what is wrong with the problem.  When pasting code, the underlines before and after the 'dict' disappeared. OK, how to send you code?

**Comment by clockwiser** [comment]
@chengs2000 ,

There are links of using copy_model.

https://github.com/yusuketomoto/chainer-fast-neuralstyle/blob/master/create_chainer_model.py

**Comment by chengs2000** [comment]
@clockwiser ,

Thanks. Got it! Underlines problem.
Works now.

**Comment by mitmul** [comment]
@chengs2000 @clockwiser @PixelDotZero @apple2373  Hi, thank you for trying this code. We've released the cleaned version of Faster R-CNN inference & **training** codes as ChainerCV: https://github.com/pfnet/chainercv . So, this repository has been actually deprecated. Could you try the [ChainerCV](https://github.com/pfnet/chainercv) repo instead of this code? And please throw an issue when you face a problem :) Thank you!
