### ISSUE TITLE
ValueError : batch is empty.

### ISSUE THREAD

**Issue by Paosder** [mitmul/chainer-faster-rcnn#23]
When I try to train with provided file 'training_rpn.py', it occurs ValueError : batch is empty.

The line 181 : train_mode(updater, 'rcnn', 10, 10, 10, 40) makes this error. Why batch is empty?

Anyone knows what's problem? I didn't modified anything and forward.py works gracefully.
(I also using gpu mode with single gpu)

**Comment by mitmul** [comment]
@Paosder Hi, thank you for trying this code. We've released the cleaned version of Faster R-CNN inference & **training** codes in ChainerCV: https://github.com/pfnet/chainercv . Please check the [ChainerCV](https://github.com/pfnet/chainercv) repo!
