### ISSUE TITLE
If the image is horizontally long, it does not detect the object on the right side.

### ISSUE THREAD

**Issue by nobuchiba** [mitmul/chainer-faster-rcnn#24]
Hi,

I am running Chainer and this algorithm on an Ubuntu 14.04 environment on a GTX 1080.

I tried object detection using images of several resolutions.
In an image close to a square, objects could be detected correctly,but if the image is horizontally long(e.g.1359x699), it did not detect the object on the right side.

Is there something wrong with internal processing? (Image size reduction processing, etc.)

Sincerely,

**Comment by mitmul** [comment]
@nobuchiba Hi, thank you for trying this repo. We've released the cleaned version of Faster R-CNN inference & **training** codes in ChainerCV: https://github.com/pfnet/chainercv . Please check the [ChainerCV](https://github.com/pfnet/chainercv) repo!
