### ISSUE TITLE
re-training the model

### ISSUE THREAD

**Issue by darkseed** [mitmul/chainer-faster-rcnn#5]
Hi, i was wondering if you could provide some information how to retrain the model, or provide some links to how to setup this myself.

**Comment by mitmul** [comment]
@darkseed Thank you for trying my codes. Now it's working in this branch: https://github.com/mitmul/chainer-faster-rcnn/tree/training

**Comment by nicedi** [comment]
@mitmul Thank you for providing Chainer version code of faster-rcnn. I downloaded the training branch ,read the code and trained the model. I found two issues. 
1.  the 'VGG16_faster_rcnn_final.model' can not be loaded, the error message is: KeyError: 'RPN/rpn_conv_3x3/W is not a file in the archive'
2. The FasterRCNN class returns four kinds of loss, so the  RPN and Fast-RCNN models can be trained jointly. I write some code to train the model, however I found that after training the 'conv5_3' feature all becomes negative, as a result,after 'relu5_3' layer the feature all becomes zero. Is this a training problem or model problem?
I use Chainer 1.13, the optimizer is MomentumSGD with learning rate 0.00001 and WeightDecay 0.0005. I trained 6 epoch on VOC2007 train+val.

**Comment by pauaribeiro** [comment]
@nicedi Can u please share you code ? I need to train a new dataset too.

Regards,
Paulo

**Comment by mitmul** [comment]
@darkseed @nicedi @pauaribeiro Hi, thank you for trying this chainer-faster-rcnn codes. We've released the new clean & simple & reliable (it surely reproduced the paper result) version of Faster R-CNN inference & training codes as ChainerCV: https://github.com/pfnet/chainercv . Please check the ChainerCV repo!
