### ISSUE TITLE
Fine Tuning 

### ISSUE THREAD

**Issue by moh3th1** [mitmul/chainer-faster-rcnn#7]
How to fine tune your model?
I don't have sufficient data to retrain your model from scratch.
I want to fine tune your model on my data which has only two classes ?

**Comment by clockwiser** [comment]
The model constructor has num_classes parameter. Guess changing the number of classes is first step of fine tuning.

**Comment by mitmul** [comment]
@moh3th1 Hi, thank you for trying this chainer-faster-rcnn codes. We've released the new clean & simple & reliable (it surely reproduced the paper result) version of Faster R-CNN inference & training codes as ChainerCV: https://github.com/pfnet/chainercv . Please check the ChainerCV repo!
