### ISSUE TITLE
Mismatch docker caffe

### ISSUE THREAD

**Issue by SoraLab** [mitmul/chainer-faster-rcnn#9]
In docker/install_caffe_docker.sh, "cd caffe/docker; make cpu_standalone" (L33).

But, In docker/Dockerfile, "FROM caffe:gpu" (L1).

Mismatch docker image of caffe:cpu and caffe:gpu.

**Comment by mitmul** [comment]
The above commit fixes the problem you pointed out?

**Comment by SoraLab** [comment]
Yes, about change of docker/Dockerfile.

By the way, why do you install nvidia-docker for caffe:cpu in install_caffe_docker.sh?
